# Generated by Django 3.1.12 on 2024-12-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('head_text', models.JSONField()),
                ('description_text', models.JSONField()),
                ('logo', models.FileField(upload_to='fourbox/logos/')),
            ],
        ),
    ]
