# Generated by Django 3.1.12 on 2024-12-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_fourbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourbox',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='fourbox/logos/'),
        ),
    ]
