# Generated by Django 3.1.12 on 2024-12-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_howwework'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowWeWorkWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_text_one', models.JSONField()),
                ('description_text_one', models.JSONField()),
                ('head_text_two', models.JSONField()),
                ('description_text_two', models.JSONField()),
                ('head_text_three', models.JSONField()),
                ('description_text_three', models.JSONField()),
            ],
        ),
    ]
