# Generated by Django 3.1.12 on 2024-12-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_meetourdoctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='OurDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_text', models.JSONField()),
                ('description_text', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='testimonials/profile_images/')),
                ('back_image', models.ImageField(upload_to='testimonials/back_images/')),
                ('name', models.JSONField()),
                ('description', models.JSONField()),
                ('country', models.JSONField()),
            ],
        ),
    ]
