# Generated by Django 3.1.12 on 2024-12-17 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_ourblog_ourdepartment_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_text', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='FaqHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.JSONField()),
                ('header_description', models.JSONField()),
                ('header_photo', models.ImageField(upload_to='headers/')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_text', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUsBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_image', models.ImageField(upload_to='why_choose_us_back_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='why_choose_us_card_logos/')),
                ('head_text', models.JSONField()),
                ('description_text', models.JSONField()),
                ('why_choose_us_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='content.whychooseusbox')),
            ],
        ),
    ]
